import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import { CookieBanner } from "@/components/cookieBanner";
import { Toaster } from "react-hot-toast";
import { Footer } from "../components/layout/footer";
import { Sidebar } from "../components/layout/sidebar";
import { Header } from "../components/layout/header";
import { validateRequest } from "../lib/lucia";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { user } = await validateRequest();
  return (
    <html suppressHydrationWarning>
      <head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </head>
      <body>
        <ThemeProvider>
          {user && (
            <Sidebar>
              <div className="flex flex-col min-h-screen">
                <Header />
                <main className="flex-grow">{children}</main>
                <Footer />
              </div>
            </Sidebar>
          )}
          {!user && (
            <div className="flex flex-col min-h-screen">
              <Header />
              <main className="flex-grow">{children}</main>
              <Footer />
            </div>
          )}

          <CookieBanner />
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
