import { createEnv } from "@t3-oss/env-nextjs";
import { z } from "zod";

export const env = createEnv({
  server: {
    NODE_ENV: z.string().optional(),
    APP_NAME: z.string().min(1),
    APP_URL: z.string().min(1),
    SECRET_KEY: z.string().min(1),
    DATABASE_URL: z.string().min(1),
    ENABLE_MAIL_SERVICE: z.boolean().optional(),
    MAIL_SERVICE_TYPE: z.enum(['resend', 'console']).optional(),
    ...(process.env.ENABLE_MAIL_SERVICE === 'true' && process.env.MAIL_SERVICE_TYPE === 'resend' ? {
      RESEND_API_KEY: z.string().min(1),
      RESEND_FROM_EMAIL: z.string().min(1),
      RESEND_FROM_NAME: z.string().min(1),
    } : {}),
    AUTH_SEND_VERIFICATION_EMAIL: z.boolean().optional(),
    // DB_AUTH_TOKEN: z.string().optional(),
    // GOOGLE_CLIENT_ID: z.string().min(1),
    // GOOGLE_CLIENT_SECRET: z.string().min(1),
    GITHUB_CLIENT_SECRET: z.string().optional(),
    GITHUB_CLIENT_ID: z.string().optional(),
    // HOST_NAME: z.string().min(1),
    // EMAIL_FROM: z.string().min(1),
    // EMAIL_SERVER_HOST: z.string().min(1),
    // EMAIL_SERVER_PORT: z.string().min(1),
    // EMAIL_SERVER_USER: z.string().min(1),
    // EMAIL_SERVER_PASSWORD: z.string().min(1),
  },
  client: {},
  runtimeEnv: {
    NODE_ENV: process.env.NODE_ENV,
    APP_NAME: process.env.APP_NAME,
    APP_URL: process.env.APP_URL,
    SECRET_KEY: process.env.SECRET_KEY,
    DATABASE_URL: process.env.DATABASE_URL,
    ENABLE_MAIL_SERVICE: process.env.ENABLE_MAIL_SERVICE === 'true',
    MAIL_SERVICE_TYPE: process.env.MAIL_SERVICE_TYPE,
    RESEND_API_KEY: process.env.RESEND_API_KEY,
    RESEND_FROM_EMAIL: process.env.RESEND_FROM_EMAIL,
    RESEND_FROM_NAME: process.env.RESEND_FROM_NAME,
    AUTH_SEND_VERIFICATION_EMAIL: process.env.AUTH_SEND_VERIFICATION_EMAIL === 'true',
    // DB_AUTH_TOKEN: process.env.DB_AUTH_TOKEN,
    // GOOGLE_CLIENT_ID: process.env.GOOGLE_CLIENT_ID,
    // GOOGLE_CLIENT_SECRET: process.env.GOOGLE_CLIENT_SECRET,
    // HOST_NAME: process.env.HOST_NAME,
    // EMAIL_SERVER_PASSWORD: process.env.EMAIL_SERVER_PASSWORD,
    // EMAIL_FROM: process.env.EMAIL_FROM,
    // EMAIL_SERVER_HOST: process.env.EMAIL_SERVER_HOST,
    // EMAIL_SERVER_PORT: process.env.EMAIL_SERVER_PORT,
    // EMAIL_SERVER_USER: process.env.EMAIL_SERVER_USER,
    GITHUB_CLIENT_SECRET: process.env.GITHUB_CLIENT_SECRET,
    GITHUB_CLIENT_ID: process.env.GITHUB_CLIENT_ID,
  },
});